spring:
  datasource:
    url: jdbc:h2:mem:tasksdatabase;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
  jpa:
#    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.H2Dialect
